format_version: 10
pipelines:
  my_pipeline:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-225a7e7:
        git: https://github.com/wfejj/simple-app
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - my_stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          my_job:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - compile
                command: mvn
                run_if: passed
